import { DrainageReport, HotspotCluster, WardInfo } from './niraTypes';

export const KOCHI_WARDS: WardInfo[] = [
  {
    ward_number: 24,
    ward_name: 'Vyttila Mobility Hub Junction',
    officer_in_charge: 'K. S. Rajesh (AE Drainage)',
    officer_phone: '+91 98471 20024',
    active_tickets: 5,
    resolved_tickets: 18,
  },
  {
    ward_number: 35,
    ward_name: 'Kadavanthra Canal Road',
    officer_in_charge: 'M. Somanathan (Overseer)',
    officer_phone: '+91 94470 35035',
    active_tickets: 4,
    resolved_tickets: 14,
  },
  {
    ward_number: 12,
    ward_name: 'Fort Kochi Heritage Trench',
    officer_in_charge: 'Anitha Roy (Junior Engineer)',
    officer_phone: '+91 98952 12012',
    active_tickets: 2,
    resolved_tickets: 22,
  },
  {
    ward_number: 40,
    ward_name: 'Edappally Toll Canal',
    officer_in_charge: 'P. V. Haridas (Assistant Executive Engineer)',
    officer_phone: '+91 97455 40040',
    active_tickets: 6,
    resolved_tickets: 11,
  },
  {
    ward_number: 28,
    ward_name: 'Kaloor Subhash Bose Road',
    officer_in_charge: 'T. K. Salim (Sanitation Inspector)',
    officer_phone: '+91 98460 28028',
    active_tickets: 3,
    resolved_tickets: 19,
  },
];

export const INITIAL_NIRA_REPORTS: DrainageReport[] = [
  {
    id: 'nr-101',
    ticket_code: 'NIRA-WYT-8821',
    photo_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
    issue_type: 'BLOCKED_STORM_DRAIN',
    severity: 'CRITICAL',
    ward: 'Vyttila',
    ward_number: 40,
    authority: 'Kochi Municipal Corporation (KMC) (East Zone)',
    selection_method: 'GPS_AUTO',
    detection_method: 'POLYGON_CONTAINMENT',
    priority_score: 92,
    priority_explanation: 'Urgent Hazard: Severe blockage on major arterial corridor with high flood risk. Mandates rapid crew dispatch within 3h SLA.',
    sla_hours: 3,
    status: 'ESCALATED',
    lat: 9.9674,
    lng: 76.3160,
    description: 'Heavy silt accumulation and plastic clogging in main storm drain near metro pillar 842 causing waterlogging on SA Road.',
    landmark: 'Opposite Mobility Hub Gate 2',
    reporter_name: 'Arjun Menon',
    reporter_phone: '+91 98470 11223',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    escalated_reason: 'Unresolved for 3+ hours during heavy monsoon downpour near hospital emergency corridor.',
    assigned_officer: 'Er. Manoj Kumar K. (Assistant Engineer)',
    assigned_crew: 'KMC Rapid Desilting Jet Crew 04',
  },
  {
    id: 'nr-102',
    ticket_code: 'NIRA-KDV-4412',
    photo_url: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80',
    issue_type: 'SILT_ACCUMULATION',
    severity: 'HIGH',
    ward: 'Kadavanthra',
    ward_number: 24,
    authority: 'Kochi Municipal Corporation (KMC) (Central Zone)',
    selection_method: 'GPS_AUTO',
    detection_method: 'POLYGON_CONTAINMENT',
    priority_score: 78,
    priority_explanation: 'Moderate Hazard: Silt accumulation restricting canal outflow. Standard 6h SLA response.',
    sla_hours: 6,
    status: 'IN_PROGRESS',
    lat: 9.9674,
    lng: 76.2998,
    description: 'Concrete slab cracked and fallen into drain channel, blocking 70% water flow towards Chilavannoor Lake.',
    landmark: 'Near Kaloor-Kadavanthra Road Signal',
    reporter_name: 'Deepa Varma',
    reporter_phone: '+91 94471 55667',
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    assigned_officer: 'Er. Rajesh Menon (Assistant Engineer)',
    assigned_crew: 'KMC Suction Jet Unit 02',
  },
  {
    id: 'nr-103',
    ticket_code: 'NIRA-FTK-9901',
    photo_url: 'https://images.unsplash.com/photo-1590059301072-a162235c5c0d?auto=format&fit=crop&w=800&q=80',
    issue_type: 'GARBAGE_DUMPING',
    severity: 'MEDIUM',
    ward: 'Fort Kochi',
    ward_number: 12,
    authority: 'Kochi Municipal Corporation (KMC) (West Zone)',
    selection_method: 'MAP_MANUAL',
    detection_method: 'POLYGON_CONTAINMENT',
    priority_score: 64,
    priority_explanation: 'Commercial waste dumped directly into side gutter. Scheduled for clearance within 12h SLA.',
    sla_hours: 12,
    status: 'ASSIGNED',
    lat: 9.9650,
    lng: 76.2420,
    description: 'Commercial waste dumped directly into side gutter causing foul smell and localized overflow during high tide.',
    landmark: 'Bastian Bungalow Lane',
    reporter_name: 'Francis Xavier',
    reporter_phone: '+91 98952 88990',
    created_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    assigned_officer: 'Er. Sunitha V. (Assistant Engineer)',
  },
  {
    id: 'nr-104',
    ticket_code: 'NIRA-EDP-1144',
    photo_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    issue_type: 'BROKEN_CULVERT',
    severity: 'HIGH',
    ward: 'Edappally',
    ward_number: 35,
    authority: 'Kochi Municipal Corporation (KMC) (North Zone)',
    selection_method: 'MAP_MANUAL',
    detection_method: 'POLYGON_CONTAINMENT',
    priority_score: 85,
    priority_explanation: 'Culvert structural breach on high traffic corridor. 6h SLA response.',
    sla_hours: 6,
    status: 'OPEN',
    lat: 10.0240,
    lng: 76.3120,
    description: 'Underpass culvert wall collapsed after heavy truck passing. Road shoulder sinking.',
    landmark: 'Edappally Toll Junction East Side',
    reporter_name: 'Rahul Nair',
    reporter_phone: '+91 97455 33221',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    assigned_officer: 'Er. Anoop Thomas (Assistant Engineer)',
  },
  {
    id: 'nr-105',
    ticket_code: 'NIRA-KLR-7733',
    photo_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    issue_type: 'SEWAGE_OVERFLOW',
    severity: 'LOW',
    ward: 'Kaloor',
    ward_number: 28,
    authority: 'Kochi Municipal Corporation (KMC) (Central Zone)',
    selection_method: 'GPS_AUTO',
    detection_method: 'POLYGON_CONTAINMENT',
    priority_score: 45,
    priority_explanation: 'Routine issue: Minor overflow resolved. Standard clearance protocol.',
    sla_hours: 24,
    status: 'RESOLVED',
    lat: 9.9940,
    lng: 76.2980,
    description: 'Minor overflow resolved by suction jet vehicle. Drain desilted and cleared.',
    landmark: 'Behind Kaloor Bus Stand',
    reporter_name: 'Suresh Kumar',
    reporter_phone: '+91 98460 77889',
    created_at: new Date(Date.now() - 1000 * 60 * 1440).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    assigned_officer: 'Er. Preetha K. (Executive Engineer)',
    assigned_crew: 'KMC Suction Jet Unit 02',
    resolution_photo_url: 'https://images.unsplash.com/photo-1590059301072-a162235c5c0d?auto=format&fit=crop&w=800&q=80',
    resolved_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    resolution_notes: 'Culvert desilted using high pressure jetting unit. Water flow restored 100%.',
  },
];

export const INITIAL_HOTSPOT_CLUSTERS: HotspotCluster[] = [
  {
    id: 'hs-1',
    ward: 'Ward 24 - Vyttila Mobility Hub Junction',
    ward_number: 24,
    report_count: 7,
    risk_level: 'CRITICAL',
    center_lat: 9.9674,
    center_lng: 76.2998,
    location_name: 'SA Road & Mobility Hub Arterial Drain',
    last_reported: '15 mins ago',
  },
  {
    id: 'hs-2',
    ward: 'Ward 40 - Edappally Toll Canal',
    ward_number: 40,
    report_count: 5,
    risk_level: 'HIGH',
    center_lat: 10.0261,
    center_lng: 76.3125,
    location_name: 'Edappally Toll Bypass Culvert Zone',
    last_reported: '45 mins ago',
  },
  {
    id: 'hs-3',
    ward: 'Ward 35 - Kadavanthra Canal Road',
    ward_number: 35,
    report_count: 4,
    risk_level: 'MODERATE',
    center_lat: 9.9612,
    center_lng: 76.3015,
    location_name: 'Kadavanthra - Chilavannoor Feeder Line',
    last_reported: '2 hours ago',
  },
];
